export const ADMIN_DASH_TODAY_INSULIN_REQUEST = "ADMIN_DASH_TODAY_INSULIN_REQUEST"
export const ADMIN_DASH_TODAY_INSULIN_SUCCESS = "ADMIN_DASH_TODAY_INSULIN_SUCCESS"
export const ADMIN_DASH_TODAY_INSULIN_FAIL = "ADMIN_DASH_TODAY_INSULIN_FAIL"

export const ADMIN_DASH_WEEK_AVERAGE_REQUEST = "ADMIN_DASH_WEEK_AVERAGE_REQUEST"
export const ADMIN_DASH_WEEK_AVERAGE_SUCCESS = "ADMIN_DASH_WEEK_AVERAGE_SUCCESS"
export const ADMIN_DASH_WEEK_AVERAGE_FAIL = "ADMIN_DASH_WEEK_AVERAGE_FAIL"

export const ADMIN_DASH_THREE_MONTH_AVERAGE_INSULIN_REQUEST = "ADMIN_DASH_THREE_MONTH_AVERAGE_INSULIN_REQUEST"
export const ADMIN_DASH_THREE_MONTH_AVERAGE_INSULIN_SUCCESS = "ADMIN_DASH_THREE_MONTH_AVERAGE_INSULIN_SUCCESS"
export const ADMIN_DASH_THREE_MONTH_AVERAGE_INSULIN_FAIL = "ADMIN_DASH_THREE_MONTH_AVERAGE_INSULIN_FAIL"

export const ADMIN_DASH_DEVICE_STATUS_REQUEST = "ADMIN_DASH_DEVICE_STATUS_REQUEST"
export const ADMIN_DASH_DEVICE_STATUS_SUCCESS = "ADMIN_DASH_DEVICE_STATUS_SUCCESS"
export const ADMIN_DASH_DEVICE_STATUS_FAIL = "ADMIN_DASH_DEVICE_STATUS_FAIL"