export const  ADMIN_LOGIN_MOBILE = "ADMIN_LOGIN_MOBILE" ;
export const  ADMIN_LOGIN_EMAIL = "ADMIN_LOGIN_EMAIL" ;
export const  ADMIN_REGISTER = "ADMIN_REGISTER";
// export default  ADMIN_LOGIN = "ADMIN_LOGIN"